### ISSUE TITLE
V4 not compatible with Ubuntu 20.04

### ISSUE THREAD

**Issue by jdreesen** [cinatic/gitlab-extension#12]
I'm new to Gnome Shell Extensions and just installed this extension via the button on https://extensions.gnome.org/extension/3535/gitlab-extension/, but sadly it doesn't work. 

After a bit of debugging, it seems that V4 uses JavaScript language features that are not supported:
`journalctl` logs a `JS ERROR: Extension gitlab-extension@infinicode.de: SyntaxError: expected expression, got '.' @ ~/.local/share/gnome-shell/extensions/gitlab-extension@infinicode.de/helpers/fetch.js:21`

It seems that the optional chaining operator is only supported since `gjs` [v1.65.90](https://gitlab.gnome.org/GNOME/gjs/-/tags/1.65.90).

---

Versions of my System:
- `lsb_release -d`: Ubuntu 20.04.3 LTS
- `gnome-shell --version`: GNOME Shell 3.36.9
- `gjs --version`: gjs 1.64.5

**Comment by cinatic** [comment]
i think it is because of includes or some other ES6 syntax, i updated the compatible shell versions, sorry for the inconvenience
