### ISSUE TITLE
Update for GNOME 45

### ISSUE THREAD

**Issue by fudio101** [cinatic/gitlab-extension#20]
Can i use this extension for GNOME version 45

**Comment by cinatic** [comment]
yes but you need to use the release version or clone and run `make install`

**Comment by nafg** [comment]
Why not publish it to extensions.gnome.org?

**Comment by cinatic** [comment]
The last version is in the review process, but because it's a bit annoying I don't feel like dealing with it at the moment. I think eg.com is basically open, feel free to upload it by yourself

**Comment by nafg** [comment]
eg.com?

**Comment by nafg** [comment]
What is eg.com

**Comment by nafg** [comment]
And what do you mean about the review process
