### ISSUE TITLE
Layout issues when having many projects in the list

### ISSUE THREAD

**Issue by brpaz** [cinatic/gitlab-extension#5]
Nice extension ;)

I found out a layout issue, when you have many projects (more than 10 in my case) the project cards start  overflowing from the container box.

Maybe limiting the visible projects  (max 10 maybe and reduce a little de margin between each card), or add scroll to the box.

**Comment by cinatic** [comment]
thanks, can you provide me a screenshot and tell me which gnome-shell version, theme and os you are using?

The result list is a ScrollView, maybe in other themes / versions a default height is missing or something:

![image](https://user-images.githubusercontent.com/2721787/98586644-49fcb080-22c9-11eb-9c69-89ec913ae61e.png)

**Comment by brpaz** [comment]
Here it is the screenshot:

![Screenshot 2020-11-09 22:03:09](https://user-images.githubusercontent.com/184563/98602005-b4b4e880-22d7-11eb-9b2e-020634d5f702.png)

Comparing to your screenshot, mine is taking 100% height of my screen.

Feodra 32 with Gnome 3.36 and default Adawita theme.

**Comment by cinatic** [comment]
figured out that i had another test extension which has overwritten my stylesheet, this is fixed with #6
