### ISSUE TITLE
All projects shown instead of only owned projects

### ISSUE THREAD

**Issue by dark-saga** [cinatic/gitlab-extension#7]
Today I started to see other repositories and not mine...

![2020-12-09_19-57](https://user-images.githubusercontent.com/6320166/101661146-fe206100-3a58-11eb-80b9-535f511ee2c2.png)

**Comment by cinatic** [comment]
oops =D, i accidentally left the `owned` flag at 0, this will be anyhow configurable in the next release.

By now i would suggest you to change `owned: 0` to `owned: 1` directly in
`~/.local/share/gnome-shell/extensions/gitlab-extension@infinicode.de/services/gitlab.js`

after that reload shell

**Comment by dark-saga** [comment]
OK it fixed the issue. Thanks.

**Comment by lig** [comment]
it could be beneficial to have this as an option for private instances

**Comment by cinatic** [comment]
configurable now per account in the settings
